<?php
$title = 'Country';
$this->headTitle($title);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<p>
    <a href="<?php echo $this->url('country', array('action'=>'add'));?>">Add new country</a>
</p>

<table class="table">
<tr>
    <th>Id</th>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>Action</th>
</tr>
<?php foreach ($countries as $province) : ?>
<tr>
    <td><?php echo $this->escapeHtml($province->id);?></td>
    <td>
        <a href="<?php echo $this->url('country',
            array('action'=>'view', 'id' => $province->id));?>"><?php echo $province->name; ?></a>        
    </td>
    <td><?php echo $this->escapeHtml($province->abbreviation);?></td>
    <td>
        <a href="<?php echo $this->url('country',
            array('action'=>'view', 'id' => $province->id));?>">View</a>
        | <a href="<?php echo $this->url('country',
            array('action'=>'edit', 'id' => $province->id));?>">Edit</a>
    </td>
</tr>
<?php endforeach; ?>
</table>