<?php
$title = 'County Details';
$this->headTitle($title);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<p>
    <a href="<?php echo $this->url('country', array('action'=>'index'));?>">Back to country list</a>
    | <a href="<?php echo $this->url('country', array('action'=>'edit', 'id'=>$country->id));?>">Edit Country</a>
    | <a href="<?php echo $this->url('province', array('action'=>'add', 'id'=>$country->id));?>">Add Province</a>
</p>

<dl class="dl-horizontal">
    <dt>Country:</dt>
    <dd><?php echo $country->name; ?></dd>
    <dt>Abbreviation:</dt>
    <dd><?php echo $country->abbreviation; ?></dd>
</dl>

<strong>Provinces:</strong>
<table class="table table-striped">
<thead>
    <th>Id</th>
    <th>Name</th>
    <th>Abbreviation</th>
</thead>

<?php
    $provinces = $country->province;
?>

<?php foreach ($provinces as $province) : ?>
<tr>
    <td><?php echo $this->escapeHtml($province->id);?></td>
    <td>
        <a href="<?php echo $this->url('province',
            array('action'=>'view', 'id' => $province->id));?>"><?php echo $province->name; ?></a>        
    </td>
    <td><?php echo $this->escapeHtml($province->abbreviation);?></td>
</tr>
<?php endforeach; ?>
</table>