<?php
// module/Album/view/album/album/add.phtml:

$title = 'Register User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));

$profile = $form->get('user_profile');
echo $this->formHidden($profile->get('id'));
echo $this->formRow($profile->get('first_name'));
echo $this->formRow($profile->get('last_name'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();