<?php
$title = 'Semester';
$this->headTitle($title);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<p>
    <a href="<?php echo $this->url('semester', array('action'=>'add'));?>">Add New Semester</a>
</p>

<table class="table">
<tr>
    <th>Semester</th>
    <th>School Year</th>
    <th>Description</th>
    <th>Action</th>
</tr>
<?php foreach ($semesters as $semester) : ?>
<tr>
    <td><?php echo $this->escapeHtml($semester->semester);?></td>
    <td><?php echo $this->escapeHtml($semester->school_year);?></td>
    <td><?php echo $this->escapeHtml($semester->description);?></td>
    <td>
        <a href="<?php echo $this->url('semester',
            array('action'=>'view', 'id' => $semester->id));?>">View</a>
        | <a href="<?php echo $this->url('semester',
            array('action'=>'edit', 'id' => $semester->id));?>">Edit</a>
    </td>
</tr>
<?php endforeach; ?>
</table>