<?php
$title = 'Semester Detail';
$this->headTitle($title);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<p>
    <a href="<?php echo $this->url('semester', array('action'=>'index'));?>">Back to List</a>
    | <a href="<?php echo $this->url('semester', array('action'=>'edit', 'id'=>$semester->id));?>">Edit Semester</a>
    | <a href="<?php echo $this->url('semester', array('action'=>'add_offer', 'id'=>$semester->id));?>">Add Offer</a>
</p>

<dl class="dl-horizontal">
    <dt>Semester:</dt>
    <dd><?php echo $semester->semester; ?></dd>
    <dt>School Year:</dt>
    <dd><?php echo $semester->school_year; ?></dd>
    <dt>Description:</dt>
    <dd><?php echo $semester->description; ?></dd>
</dl>

<table class="table">
<tr>
    <th>Subject</th>
    <th>Code</th>
    <th>Name</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($semester->offers as $offer) : ?>
<tr>
    <td><?php echo $this->escapeHtml($offer->subject->short_name);?></td>
    <td><?php echo $this->escapeHtml($offer->code);?></td>
    <td><?php echo $this->escapeHtml($offer->name);?></td>
    <td><?php echo $this->escapeHtml($offer->description);?></td>
    <td>
        <a href="<?php echo $this->url('semester',
            array('action'=>'view', 'id' => $offer->id));?>">View</a>
        | <a href="<?php echo $this->url('semester',
            array('action'=>'edit', 'id' => $offer->id));?>">Edit</a>
    </td>
</tr>
<?php endforeach; ?>
</table>